parameters:
    # Email immeditely Communication Handler
    bsp.communication.email_immediately_communication_type_handler.class: BSP\CommunicationBundle\Handler\EmailImmediatelyCommunicationTypeHandler

    # Listener Class
    bsp.communication.listener.communication.class: BSP\CommunicationBundle\Listener\CommunicationListener

    # Communication Manipulator
    bsp.communication.manipulator.class: BSP\CommunicationBundle\Manipulator\CommunicationManipulator

    # Communication type Provider
    bsp.communication.communication_type_sender_provider.class: BSP\CommunicationBundle\Provider\CommunicationTypeSenderProvider

services:
    # Email immeditely Communication Handler
    bsp.communication.communication_type_handler.email_immediately:
        class: %bsp.communication.email_immediately_communication_type_handler.class%
        calls:
            - [ setMailer, [@mailer] ]
        tags:
            - { name: bsp.communication.communication_type_handler }

    # Listeners
    bsp.communication.listener.communication:
        class: %bsp.communication.listener.communication.class%
        calls:
            - [ setCommunicationManipulator, [@bsp.communication.manipulator] ]
            - [ setCommunicationManager, [@bsp.communication.communication_manager] ]
            - [ setCommunicationTypeSenderProvider, [@bsp.communication.communication_type_sender_provider] ]
        tags:
            - { name: kernel.event_listener, event: bsp.communication.communication_created, method: onCreateCommunication }
            - { name: kernel.event_listener, event: bsp.communication.communication_sended, method: onSendCommunication }
            - { name: kernel.event_listener, event: bsp.communication.communication_status_changed, method: onChangeStatusCommunication }

    # Communication Manipulator
    bsp.communication.manipulator:
        class: %bsp.communication.manipulator.class%
        arguments:
            - @bsp.communication.communication_manager
            - @event_dispatcher

    # Communication type Provider
    bsp.communication.communication_type_sender_provider:
        class: %bsp.communication.communication_type_sender_provider.class%

